import { initializeApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getDatabase, ref, set, get, onValue, update, push } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js";
const firebaseConfig={apiKey:"AIzaSyBF4A5AGcR0eb5ZsuEiUG-Gg9Vfr119yg",authDomain:"kelime-oyunu-57a0b.firebaseapp.com",databaseURL:"https://kelime-oyunu-57a0b-default-rtdb.firebaseio.com",projectId:"kelime-oyunu-57a0b",storageBucket:"kelime-oyunu-57a0b.firebasestorage.app",messagingSenderId:"580383166978",appId:"1:580383166978:web:f0d428220ab83e33bb4d1b",measurementId:"G-PKEB0K17PX"};
const db=getDatabase(initializeApp(firebaseConfig));
let roomId=null,playerNumber=null,currentRound=1,timerInterval=null,gameFinished=false,submitting=false,seenEmojiIds=new Set(),roomUnsubscribe=null,lastEmojiAt=0,soundEnabled=localStorage.getItem("kelimeSound")!=="off";
const $=id=>document.getElementById(id),menu=$("menu"),waiting=$("waiting"),game=$("game"),result=$("result"),nameInput=$("nameInput"),roomInput=$("roomInput"),roomCodeDisplay=$("roomCodeDisplay"),waitingText=$("waitingText"),wordInput=$("wordInput"),status=$("status"),roundNumber=$("roundNumber"),roundTotal=$("roundTotal"),timerEl=$("timer"),playerCountLabel=$("playerCountLabel"),playersTable=$("playersTable"),currentWords=$("currentWords"),currentWordsBody=$("currentWordsBody"),historyList=$("historyList"),emojiFeed=$("emojiFeed"),resultTitle=$("resultTitle"),resultText=$("resultText"),finalResult=$("finalResult"),resultBadge=$("resultBadge"),playerCountSelect=$("playerCount"),submitWord=$("submitWord"),soundToggle=$("soundToggle"),scoreTable=$("scoreTable"),rematchBtn=$("rematchBtn"),roundStats=$("roundStats");
function generateRoomCode(){const c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>c[Math.floor(Math.random()*c.length)]).join("");}
function normalizeWord(w){return String(w||"").trim().toLocaleLowerCase("tr-TR").replace(/[ıİiI]/g,"i").replace(/[ğĞ]/g,"g").replace(/[şŞ]/g,"s").replace(/[üÜ]/g,"u").replace(/[öÖ]/g,"o").replace(/[çÇ]/g,"c").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/g,"");}
function escapeHtml(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML;}function playerPath(n=playerNumber){return `player${n}`;}function roomLink(){return `${location.origin}${location.pathname}?room=${roomId}`;}function stopTimer(){if(timerInterval){clearInterval(timerInterval);timerInterval=null;}}function getPlayers(r){return Array.from({length:Number(r.maxPlayers||2)},(_,i)=>({number:i+1,...(r[`player${i+1}`]||{})}));}function getJoinedPlayers(r){return getPlayers(r).filter(p=>p.joined);}
function playTone(kind="click"){if(!soundEnabled)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();const f=kind==="success"?760:kind==="error"?180:kind==="warning"?600:kind==="win"?920:420;o.frequency.value=f;g.gain.value=kind==="warning"?.035:.045;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.12);}catch(e){}}
function setStatus(t){if(status)status.textContent=t;}
function startTimer(r){stopTimer();const round=Number(r.round||1);if(gameFinished||r.finished||r[playerPath()]?.words?.[round])return;const started=Number(r.roundStartedAt||Date.now()),total=Number(r.roundDuration||60);let lastLeft=total+1;const tick=()=>{const left=Math.max(0,total-M.floor((Date.now()-started)/1000));if(timerEl)timerEl.textContent=String(left);if(timerEl)timerEl.classList.toggle("timer-warning",left<=10);if(left<=10&&left!==lastLeft&&left>0){if(left===10)setStatus("⚠️ SON 10 SANİYE!");playTone("warning");}lastLeft=left;if(left<=0){stopTimer();advanceAfterTimeout(round);}};tick();timerInterval=setInterval(tick,1000);}
async function advanceAfterTimeout(round){const s=await get(ref(db,`rooms/${roomId}`));if(!s.exists())return;const r=s.val();if(r.finished||Number(r.round)!==round)return;const total=Number(r.totalRounds||5);if(round<total)await update(ref(db,`rooms/${roomId}`),{round:round+1,roundStartedAt:Date.now()});else await update(ref(db,`rooms/${roomId}`),{finished:true,winnerRound:0,finishReason:"timeout",finishedRound:round});}
function settingsForPlayers(n){return {2:{rounds:5,seconds:60},3:{rounds:8,seconds:90},4:{rounds:12,seconds:120},5:{rounds:15,seconds:150}}[n];}
$("createRoom").addEventListener("click",async()=>{const name=nameInput.value.trim()||"Oyuncu 1",maxPlayers=Number(playerCountSelect.value),settings=settingsForPlayers(maxPlayers);roomId=generateRoomCode();playerNumber=1;gameFinished=false;currentRound=1;seenEmojiIds.clear();const players={};for(let i=1;i<=5;i++)players[`player${i}`]={joined:i===1,name:i===1?name:`Oyuncu ${i}`,words:{},score:0,streak:0,bestStreak:0,emojiCount:0};await set(ref(db,`rooms/${roomId}`),{...players,maxPlayers,totalRounds:settings.rounds,roundDuration:settings.seconds,round:1,roundStartedAt:Date.now(),emojis:{},finished:false,winnerRound:0,createdAt:Date.now()});menu.classList.add("hidden");waiting.classList.remove("hidden");roomCodeDisplay.textContent=roomId;listenToRoom();});
async function joinRoom(code){const roomRef=ref(db,`rooms/${code}`),snap=await get(roomRef);if(!snap.exists()){alert("Bu oda bulunamadı.");return;}const r=snap.val(),maxPlayers=Number(r.maxPlayers||2),free=Array.from({length:maxPlayers},(_,i)=>i+1).find(i=>!r[`player${i}`]?.joined);if(!free){alert("Bu oda dolu.");return;}roomId=code;playerNumber=free;gameFinished=false;const name=nameInput.value.trim()||`Oyuncu ${free}`;await update(roomRef,{[`player${free}/joined`]:true,[`player${free}/name`]:name,[`player${free}/score`]:0,[`player${free}/streak`]:0,[`player${free}/bestStreak`]:0,[`player${free}/emojiCount`]:0});menu.classList.add("hidden");listenToRoom();}
$("joinRoom").addEventListener("click",()=>{const c=roomInput.value.trim().toUpperCase();if(c)joinRoom(c);else alert("Oda kodunu gir.");});$("copyRoom").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(roomLink());alert("🔗 Davet linki kopyalandı!");}catch(e){prompt("Davet linkini kopyala:",roomLink());}});$("whatsappShare").addEventListener("click",()=>window.open(`https://wa.me/?text=${encodeURIComponent(`⚡ Kelime Düellosu'na katıl!\nOda: ${roomId}\n${roomLink()}`)}`,"_blank"));
async function submitCurrentWord(rawWord){if(submitting||gameFinished||!roomId||!playerNumber)return;const word=String(rawWord??"").trim(),normalized=normalizeWord(word);if(!normalized){setStatus("✍️ Önce bir kelime yaz.");wordInput.focus();return;}submitting=true;submitWord.disabled=true;wordInput.disabled=true;try{const roomRef=ref(db,`rooms/${roomId}`),snap=await get(roomRef);if(!snap.exists())throw new Error("ROOM_NOT_FOUND");const r=snap.val(),round=Number(r.round||1),totalRounds=Number(r.totalRounds||5),totalPlayers=Number(r.maxPlayers||2);currentRound=round;if(r.finished){setStatus("🏁 Oyun sona erdi.");return;}if(r[playerPath()]?.words?.[round]){setStatus("✅ Bu adımda kelimeni zaten gönderdin.");return;}for(let p=1;p<=totalPlayers;p++){const ws=r[`player${p}`]?.words||{};for(let i=1;i<=totalRounds;i++)if(i!==round&&ws[i]&&normalizeWord(ws[i])===normalized){setStatus("⛔ Bu kelime daha önce kullanıldı. Başka kelime seç.");playTone("error");return;}}
const elapsed=Math.max(0,Number(r.roundDuration||60)-Math.max(0,Number(r.roundDuration||60)-Math.floor((Date.now()-Number(r.roundStartedAt||Date.now()))/1000)));await set(ref(db,`rooms/${roomId}/${playerPath()}/words/${round}`),word);const streak=Number(r[playerPath()]?.streak||0)+1;const best=Math.max(Number(r[playerPath()]?.bestStreak||0),streak);const seconds=Number(r.roundDuration||60);const speedBonus=elapsed<=Math.ceil(seconds*.25)?50:elapsed<=Math.ceil(seconds*.5)?35:elapsed<=Math.ceil(seconds*.75)?20:10;await update(ref(db,`rooms/${roomId}/${playerPath()}`),{streak,bestStreak:best,lastSpeedBonus:speedBonus,lastSubmitSeconds:elapsed});wordInput.value="";setStatus(`🟢 HAZIR — +${speedBonus} hız bonusu potansiyeli.`);playTone("success");await checkRound(round);}catch(err){console.error(err);setStatus("⚠️ Kelime gönderilemedi. Tekrar dene.");}finally{submitting=false;submitWord.disabled=false;wordInput.disabled=false;if(!gameFinished)wordInput.focus();}}
submitWord.addEventListener("click",e=>{e.preventDefault();submitCurrentWord(wordInput.value);});wordInput.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();submitCurrentWord(wordInput.value);}});
const emojiList=["😀","😂","🤣","😎","🤔","😱","😭","😡","🤯","🔥","❤️","💀","👀","👏","🙌","👍","👎","🎉","🥳","😈","😏","🤡","🫡","💪","🧠","⚡","🏆","💯","🍀","🤝","🫶","😴","😍","😮","🥶","🤩","😇","😜","🎯"];document.querySelectorAll(".emoji").forEach(btn=>btn.addEventListener("click",async e=>{e.preventDefault();if(!roomId||gameFinished)return;const now=Date.now();if(now-lastEmojiAt<330){setStatus("⏳ Emoji hız sınırı: biraz yavaşla.");return;}lastEmojiAt=now;try{const me=window.currentRoom?.[playerPath()]||{};const emojiRef=push(ref(db,`rooms/${roomId}/emojis`));await set(emojiRef,{emoji:btn.dataset.emoji,name:me.name||"Oyuncu",timestamp:now});await update(ref(db,`rooms/${roomId}/${playerPath()}`),{emojiCount:Number(me.emojiCount||0)+1});playTone();}catch(err){console.error(err);setStatus("⚠️ Emoji gönderilemedi.");}}));
async function checkRound(roundToCheck){const snap=await get(ref(db,`rooms/${roomId}`));if(!snap.exists())return;const r=snap.val(),round=Number(r.round||1);if(r.finished||round!==Number(roundToCheck))return;const players=getJoinedPlayers(r),totalRounds=Number(r.totalRounds||5);if(players.length!==Number(r.maxPlayers||2))return;const submitted=players.filter(p=>p.words?.[round]);if(submitted.length<players.length)return;const normalized=submitted.map(p=>normalizeWord(p.words[round])),counts={};normalized.forEach(w=>counts[w]=(counts[w]||0)+1);const matched=Object.keys(counts).find(w=>counts[w]>=2);if(matched){const matchedPlayers=submitted.filter(p=>normalizeWord(p.words[round])===matched);const elapsed=Math.max(0,Number(r.roundDuration||60)-Math.max(0,Number(r.roundDuration||60)-Math.floor((Date.now()-Number(r.roundStartedAt||Date.now()))/1000)));const updates={finished:true,winnerRound:round,matchedWord:matchedPlayers[0]?.words?.[round]||matched,finishedRound:round,finishReason:"match"};for(const p of matchedPlayers){const speed=Number(p.lastSpeedBonus||10),base=100,streakBonus=Math.min(100,Number(p.streak||1)*10),newScore=Number(p.score||0)+base+speed+streakBonus;updates[`${`player${p.number}`}/score`]=newScore;updates[`${`player${p.number}`}/roundPoints/${round}`]=base+speed+streakBonus;updates[`${`player${p.number}`}/matchCount`]=Number(p.matchCount||0)+1;}await update(ref(db,`rooms/${roomId}`),updates);return;}if(round<totalRounds)await update(ref(db,`rooms/${roomId}`),{round:round+1,roundStartedAt:Date.now()});else await update(ref(db,`rooms/${roomId}`),{finished:true,winnerRound:0,finishReason:"no_match",finishedRound:round});}
function renderPlayers(r){playersTable.innerHTML=getPlayers(r).map(p=>p.joined?`<tr><td>${escapeHtml(p.name||`Oyuncu ${p.number}`)}</td><td>${p.words?.[currentRound]?"🟢 HAZIR":"🟡 Düşünüyor..."}</td><td>${p.words?.[currentRound]?"🔒 Gönderildi":"—"}</td></tr>`:`<tr><td>${escapeHtml(p.name||`Oyuncu ${p.number}`)}</td><td>⏳ Bekleniyor</td><td>—</td></tr>`).join("");playerCountLabel.textContent=`${getJoinedPlayers(r).length}/${r.maxPlayers}`;}
function renderCurrentWords(r){const players=getJoinedPlayers(r),all=players.length===Number(r.maxPlayers||2)&&players.every(p=>p.words?.[currentRound]);currentWordsBody.innerHTML=players.map(p=>`<tr><th>${escapeHtml(p.name||"Oyuncu")}</th><td>${all?escapeHtml(p.words?.[currentRound]||"—"):"🔒 Gizli"}</td></tr>`).join("");currentWords.classList.toggle("hidden",!players.some(p=>p.words?.[currentRound]));}
function renderHistory(r){let html="";const players=getJoinedPlayers(r);for(let i=1;i<currentRound;i++){const vals=players.map(p=>`<span>👤 ${escapeHtml(p.name||"Oyuncu")}: <b>${escapeHtml(p.words?.[i]||"—")}</b></span>`);if(players.some(p=>p.words?.[i]))html+=`<div class="history-round"><strong>Adım ${i}</strong>${vals.join("")}</div>`;}historyList.innerHTML=html||"<p class='empty-history'>Henüz tamamlanan bir adım yok.</p>";}
function updateStatus(r){const joined=getJoinedPlayers(r),submitted=joined.filter(p=>p.words?.[currentRound]).length;if(submitted===0)setStatus("🟡 Herkes düşünüyor...");else if(submitted<joined.length)setStatus(`🟢 ${submitted}/${joined.length} oyuncu HAZIR — diğer oyuncular bekleniyor.`);else setStatus("🔍 Kelimeler kontrol ediliyor...");}
function showEmoji(item){const el=document.createElement("div");el.className="floating-emoji";el.style.top=`${Math.floor(Math.random()*210)}px`;el.style.animationDuration=`${2.8+Math.random()*1.4}s`;el.innerHTML=`<span>${escapeHtml(item.emoji)}</span><small>${escapeHtml(item.name)}</small>`;emojiFeed.appendChild(el);setTimeout(()=>el.remove(),4500);}
function updateWaitingText(r){waitingText.textContent=`${getJoinedPlayers(r).length}/${r.maxPlayers} oyuncu katıldı. Oyun tüm oyuncular katılınca başlayacak.`;}
function titleFor(p,r){const scores=getPlayers(r).filter(x=>x.joined).map(x=>Number(x.score||0));const max=Math.max(...scores,0);if(Number(p.score||0)===max&&max>0)return "👑 Kelime Ustası";if(Number(p.bestStreak||0)>=5)return "🔥 Seri Canavarı";if(Number(p.lastSpeedBonus||0)>=50)return "⚡ Hızlı Düşünen";if(Number(p.emojiCount||0)>=10)return "😂 Emoji Kralı";if(Number(p.lastSpeedBonus||0)<=10&&Number(p.lastSubmitSeconds||0)>0)return "🐢 Son Saniyeci";return "🎯 Tam İsabet";}
function renderScoreboard(r){if(!scoreTable)return;const players=getJoinedPlayers(r).sort((a,b)=>Number(b.score||0)-Number(a.score||0);scoreTable.innerHTML=players.map((p,i)=>`<tr><td>${i===0?"🥇":i===1?"🥈":i===2?"🥉":""} ${escapeHtml(p.name||`Oyuncu ${p.number}`)}</td><td><b>${Number(p.score||0)}</b></td><td>${Number(p.streak||0)} 🔥</td><td>${titleFor(p,r)}</td></tr>`).join("");}
function finishGame(r){if(gameFinished)return;gameFinished=true;stopTimer();game.classList.add("hidden");waiting.classList.add("hidden");result.classList.remove("hidden");const finishRound=Number(r.finishedRound||r.winnerRound||r.round||r.totalRounds||5),players=getJoinedPlayers(r);renderScoreboard(r);if(r.winnerRound){resultBadge.textContent="🎉";resultTitle.textContent="BAŞARILI! KELİME BULUNDU!";resultText.textContent=`Adım ${r.winnerRound}'de aynı kelime bulundu ve oyun sona erdi.`;roundStats.textContent=`🏆 Eşleşme: ${escapeHtml(r.matchedWord||"—")} · Adım ${r.winnerRound}`;finalResult.innerHTML=`<div class="winner-word"><b>Bulunan kelime:</b> ${escapeHtml(r.matchedWord||"—")}</div>`+players.map(p=>`<div><b>${escapeHtml(p.name||`Oyuncu ${p.number}`)}</b>: ${escapeHtml(p.words?.[r.winnerRound]||"Kelime gönderilmedi")} · <strong>${Number(p.score||0)} puan</strong> · ${titleFor(p,r)}</div>`).join("");playTone("win");}else{resultBadge.textContent="😔";resultTitle.textContent="BAŞARISIZ — KELİME BULUNAMADI";resultText.textContent=`Son adım (${finishRound}) tamamlandı. Oyuncuların yazdığı son kelimeler:`;roundStats.textContent=`⏱️ ${r.finishReason==="timeout"?"Süre doldu":"Son adımda eşleşme olmadı"}`;finalResult.innerHTML=`<div class="final-round-title">Son Adım ${finishRound}</div>`+players.map(p=>`<div><b>${escapeHtml(p.name||`Oyuncu ${p.number}`)}</b>: ${escapeHtml(p.words?.[finishRound]||"Kelime gönderilmedi")} · <strong>${Number(p.score||0)} puan</strong> · ${titleFor(p,r)}</div>`).join("");playTone("error");}}
function resetInputForRound(newRound){stopTimer();wordInput.disabled=false;submitWord.disabled=false;wordInput.value="";wordInput.placeholder=`Adım ${newRound} — kelimeyi yaz ve gönder...`;wordInput.focus();}
async function rematch(){if(!roomId)return;const snap=await get(ref(db,`rooms/${roomId}`));if(!snap.exists())return;const r=snap.val();const updates={finished:false,winnerRound:0,matchedWord:null,finishedRound:0,finishReason:null,round:1,roundStartedAt:Date.now(),emojis:{}};getPlayers(r).forEach(p=>{if(p.joined){updates[`player${p.number}/words`]={};updates[`player${p.number}/score`]=0;updates[`player${p.number}/streak`]=0;updates[`player${p.number}/bestStreak`]=0;updates[`player${p.number}/roundPoints`] = {};updates[`player${p.number}/emojiCount`]=0;}});await update(ref(db,`rooms/${roomId}`),updates);gameFinished=false;currentRound=1;seenEmojiIds.clear();result.classList.add("hidden");game.classList.remove("hidden");resetInputForRound(1);playTone("success");}
if(rematchBtn)rematchBtn.addEventListener("click",rematch);if(soundToggle){soundToggle.textContent=soundEnabled?"🔊 Ses Açık":"🔇 Ses Kapalı";soundToggle.addEventListener("click",()=>{soundEnabled=!soundEnabled;localStorage.setItem("kelimeSound",soundEnabled?"on":"off");soundToggle.textContent=soundEnabled?"🔊 Ses Açık":"🔇 Ses Kapalı";if(soundEnabled)playTone();});}
function listenToRoom(){if(roomUnsubscribe)roomUnsubscribe();roomUnsubscribe=onValue(ref(db,`rooms/${roomId}`),snap=>{const r=snap.val();if(!r)return;window.currentRoom=r;const joined=getJoinedPlayers(r),total=Number(r.maxPlayers||2),newRound=Number(r.round||1),roundChanged=newRound!==currentRound;updateWaitingText(r);if(joined.length===total){waiting.classList.add("hidden");game.classList.remove("hidden");}else{waiting.classList.remove("hidden");game.classList.add("hidden");}if(roundChanged){currentRound=newRound;resetInputForRound(newRound);}else{currentRound=newRound;wordInput.disabled=false;submitWord.disabled=false;}roundNumber.textContent=currentRound;roundTotal.textContent=Number(r.totalRounds||5);timerEl.textContent=String(Number(r.roundDuration||60));renderPlayers(r);renderCurrentWords(r);renderHistory(r);if(r.finished){finishGame(r);return;}updateStatus(r);if(joined.length===total){if(r[playerPath()]?.words?.[currentRound])stopTimer();else startTimer(r);}Object.entries(r.emojis||{}).forEach(([id,item])=>{if(!seenEmojiIds.has(id)){seenEmojiIds.add(id);showEmoji(item);}});});}
$("newGame").addEventListener("click",()=>location.href=location.pathname);const params=new URLSearchParams(location.search),roomParam=params.get("room");if(roomParam)roomInput.value=roomParam.toUpperCase();
