import { initializeApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getDatabase, ref, set, get, onValue, update, push } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js";
const firebaseConfig={apiKey:"AIzaSyBF4A5AGcR0eb5ZsuEiUG-Gg9Vfr119yg",authDomain:"kelime-oyunu-57a0b.firebaseapp.com",databaseURL:"https://kelime-oyunu-57a0b-default-rtdb.firebaseio.com",projectId:"kelime-oyunu-57a0b",storageBucket:"kelime-oyunu-57a0b.firebasestorage.app",messagingSenderId:"580383166978",appId:"1:580383166978:web:f0d428220ab83e33bb4d1b",measurementId:"G-PKEB0K17PX"};
const db=getDatabase(initializeApp(firebaseConfig));
let roomId=null,playerNumber=null,currentRound=1,timerInterval=null,secondsLeft=60,gameFinished=false,seenEmojiIds=new Set();
const $=id=>document.getElementById(id);const menu=$("menu"),waiting=$("waiting"),game=$("game"),result=$("result"),nameInput=$("nameInput"),roomInput=$("roomInput"),roomCodeDisplay=$("roomCodeDisplay"),waitingText=$("waitingText"),wordInput=$("wordInput"),status=$("status"),roundNumber=$("roundNumber"),word1=$("word1"),word2=$("word2"),player1Name=$("player1Name"),player2Name=$("player2Name"),score1=$("score1"),score2=$("score2"),timerEl=$("timer"),words=$("words"),resultTitle=$("resultTitle"),resultText=$("resultText"),finalScores=$("finalScores"),emojiFeed=$("emojiFeed"),historyList=$("historyList");
function generateRoomCode(){const c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>c[Math.floor(Math.random()*c.length)]).join("");}
// Karşılaştırmada büyük/küçük harf ve noktalı/noktasız Türkçe harf ayrımı tamamen yok sayılır.
function normalizeWord(w){return w.trim().toLocaleLowerCase("tr-TR").replace(/[ıİiI]/g,"i").replace(/[ğĞ]/g,"g").replace(/[şŞ]/g,"s").replace(/[üÜ]/g,"u").replace(/[öÖ]/g,"o").replace(/[çÇ]/g,"c").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/g,"");}
function roomLink(){return `${location.origin}${location.pathname}?room=${roomId}`;}function playerPath(){return playerNumber===1?"player1":"player2";}function setStatus(t){status.textContent=t;}function stopTimer(){if(timerInterval){clearInterval(timerInterval);timerInterval=null;}}
function playTone(type="click"){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=type==="success"?720:type==="error"?180:420;g.gain.value=.045;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.12);}catch(e){}}
function hasSubmitted(){return Boolean(window.currentRoom?.[playerPath()]?.words?.[currentRound]);}
function startTimer(){stopTimer();if(hasSubmitted()||gameFinished)return;secondsLeft=60;timerEl.textContent=secondsLeft;timerEl.classList.remove("timer-warning");timerInterval=setInterval(async()=>{secondsLeft--;timerEl.textContent=secondsLeft;if(secondsLeft<=10)timerEl.classList.add("timer-warning");if(secondsLeft<=0){stopTimer();if(!hasSubmitted())await submitCurrentWord("pas");}},1000);}
$("createRoom").addEventListener("click",async()=>{const name=nameInput.value.trim()||"Oyuncu 1";roomId=generateRoomCode();playerNumber=1;await set(ref(db,`rooms/${roomId}`),{player1:{joined:true,name,words:{}},player2:{joined:false,name:"Oyuncu 2",words:{}},round:1,usedWords:{},emojis:{},finished:false});menu.classList.add("hidden");waiting.classList.remove("hidden");roomCodeDisplay.textContent=roomId;listenToRoom();});
async function joinRoom(code){const snap=await get(ref(db,`rooms/${code}`));if(!snap.exists()){alert("Bu oda bulunamadı.");return;}if(snap.val().player2?.joined){alert("Bu oda dolu.");return;}roomId=code;playerNumber=2;const name=nameInput.value.trim()||"Oyuncu 2";await update(ref(db,`rooms/${code}`),{"player2/joined":true,"player2/name":name});menu.classList.add("hidden");game.classList.remove("hidden");listenToRoom();}
$("joinRoom").addEventListener("click",()=>{const c=roomInput.value.trim().toUpperCase();if(c)joinRoom(c);});$("copyRoom").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(roomLink());setStatus("🔗 Oda linki kopyalandı!");playTone();}catch(e){alert(roomLink());}});$("whatsappShare").addEventListener("click",()=>window.open(`https://wa.me/?text=${encodeURIComponent(`Kelime oyununa katıl! Oda: ${roomId}\n${roomLink()}`)}`,"_blank"));
// Yalnızca gerçek kelime gönderimi kelime hakkını tüketir.
async function submitCurrentWord(word){if(gameFinished||!roomId||!playerNumber)return;const normalized=normalizeWord(word);if(!normalized)return;const snap=await get(ref(db,`rooms/${roomId}`));if(!snap.exists())return;const r=snap.val(),used=r.usedWords||{};if(used[normalized]!==undefined){setStatus("🚫 Bu kelime daha önceki bir turda kullanıldı!");playTone("error");return;}await set(ref(db,`rooms/${roomId}/${playerPath()}/words/${currentRound}`),word.trim());await update(ref(db,`rooms/${roomId}/usedWords`),{[normalized]:currentRound});wordInput.value="";setStatus("✅ Kelimen gönderildi.");playTone("success");checkRound();}
$("submitWord").addEventListener("click",()=>submitCurrentWord(wordInput.value));wordInput.addEventListener("keydown",e=>{if(e.key==="Enter")submitCurrentWord(wordInput.value);});
document.querySelectorAll(".emoji").forEach(b=>b.addEventListener("click",async()=>{if(!roomId||gameFinished)return;const p=window.currentRoom?.[playerPath()]||{};await push(ref(db,`rooms/${roomId}/emojis`),{emoji:b.dataset.emoji,name:p.name||"Oyuncu",timestamp:Date.now()});playTone();}));
function calculateScores(r){let s1=0,s2=0;for(let i=1;i<=5;i++){const a=r.player1.words?.[i],b=r.player2.words?.[i];if(a&&b){if(normalizeWord(a)===normalizeWord(b)){s1+=10;s2+=10;}else{const p=Math.max(1,10-Math.abs(normalizeWord(a).length-normalizeWord(b).length));s1+=p;s2+=p;}}}return[s1,s2];}
async function checkRound(){const snap=await get(ref(db,`rooms/${roomId}`));if(!snap.exists())return;const r=snap.val(),a=r.player1.words?.[currentRound],b=r.player2.words?.[currentRound];if(!a||!b)return;if(normalizeWord(a)===normalizeWord(b)){await update(ref(db,`rooms/${roomId}`),{finished:true,winnerRound:currentRound});return;}if(currentRound<5&&r.round===currentRound)await update(ref(db,`rooms/${roomId}`),{round:currentRound+1});else if(currentRound>=5)await update(ref(db,`rooms/${roomId}`),{finished:true,winnerRound:0});}
function escapeHtml(v){const d=document.createElement("div");d.textContent=v;return d.innerHTML;}
function renderHistory(r){const rows=[];for(let i=1;i<currentRound;i++){const a=r.player1?.words?.[i],b=r.player2?.words?.[i];if(a||b)rows.push(`<div class="history-round"><strong>Tur ${i}</strong><span>👤 ${escapeHtml(r.player1?.name||"Oyuncu 1")}: ${escapeHtml(a||"—")}</span><span>👤 ${escapeHtml(r.player2?.name||"Oyuncu 2")}: ${escapeHtml(b||"—")}</span></div>`);}historyList.innerHTML=rows.length?rows.join(""):"<p class='empty-history'>Henüz önceki tur yok.</p>";}
function showEmoji(item){const el=document.createElement("div");el.className="floating-emoji";el.innerHTML=`<span>${escapeHtml(item.emoji)}</span><small>${escapeHtml(item.name)}</small>`;emojiFeed.appendChild(el);setTimeout(()=>el.remove(),3500);}
function finishGame(r){if(gameFinished)return;gameFinished=true;stopTimer();game.classList.add("hidden");result.classList.remove("hidden");const[s1,s2]=calculateScores(r),winRound=r.winnerRound||0;if(winRound){const a=r.player1.words?.[winRound],b=r.player2.words?.[winRound];resultTitle.textContent="🎉 KELİME BULUNDU!";resultText.textContent=`${winRound}. adımda kelime bulundu.`;finalScores.innerHTML=`<div class="found-word"><strong>${escapeHtml(r.player1.name)}</strong>: ${escapeHtml(a)}<br><strong>${escapeHtml(r.player2.name)}</strong>: ${escapeHtml(b)}</div>`;}else{resultTitle.textContent="❌ KELİME BULUNAMADI";resultText.textContent="5 adımın sonunda aynı kelime bulunamadı.";finalScores.textContent=`${r.player1.name}: ${s1} puan • ${r.player2.name}: ${s2} puan`;}}
function listenToRoom(){onValue(ref(db,`rooms/${roomId}`),snap=>{const r=snap.val();if(!r)return;window.currentRoom=r;const p1=r.player1||{},p2=r.player2||{};player1Name.textContent=`${p1.name||"Oyuncu 1"} 🧑`;player2Name.textContent=`${p2.name||"Oyuncu 2"} 🧑`;const sc=calculateScores(r);score1.textContent=sc[0];score2.textContent=sc[1];if(p1.joined&&p2.joined){waiting.classList.add("hidden");game.classList.remove("hidden");}currentRound=r.round||1;roundNumber.textContent=currentRound;renderHistory(r);const a=p1.words?.[currentRound]||"",b=p2.words?.[currentRound]||"";word1.textContent=a||"---";word2.textContent=b||"---";words.classList.toggle("hidden",!(a&&b));if(r.finished){finishGame(r);return;}const me=r[playerPath()],other=playerNumber===1?p2:p1;if(a&&b){setStatus(normalizeWord(a)===normalizeWord(b)?`🎯 KELİME BULUNDU! ${p1.name} & ${p2.name}`:`❌ Bu adımda bulunmadı • ${p1.name} & ${p2.name}`);}else if(me?.words?.[currentRound]){setStatus(`⏳ ${other.name||"Rakip"} düşünüyor...`);stopTimer();}else if(other?.words?.[currentRound]){setStatus(`🟢 ${other.name||"Rakip"} HAZIR — senin kelimeni bekliyor.`);startTimer();}else{setStatus(`🟡 ${other.name||"Rakip"} düşünüyor...`);startTimer();}});onValue(ref(db,`rooms/${roomId}/emojis`),snap=>snap.forEach(ch=>{if(!seenEmojiIds.has(ch.key)){seenEmojiIds.add(ch.key);showEmoji(ch.val());}}));}
$("newGame").addEventListener("click",()=>location.reload());const invited=new URLSearchParams(location.search).get("room");if(invited)roomInput.value=invited.toUpperCase();
